---
language: python
python:
  - "2.7"

# Install python packages for ansible and linters.
install:
  - "pip install -r requirements.txt"

# Execute linting and unit tests before running the main playbook.
# If any of these tasks fail, the entire build fails immediately.
before_script:
  - "./tests/lint.sh"
  - "echo 'brkrst3310' >> ~/vault_pass_file.txt"
  - "ansible-playbook tests/build_hosts_playbook.yml"
  - "ansible-playbook tests/unittest_playbook.yml"

# Perform some limited role testing until a better strategy for detailed
# playbook testing can be developed.
script:
  - "ansible-playbook roles/dtg/tests/test.yml -i roles/dtg/tests/inventory.yml"
...
