---
all:
  hosts:
    localhost:
  children:
    perf_routers:
      children:
        west_usa:
          hosts:
            csr1:
        east_usa:
          hosts:
            csr2:
            csr3:
...
