---
all:
  hosts:
    localhost:
  children:
    perf_routers:
      children:
        west_usa_region:
          hosts:
            csr1:
        east_usa_region:
          hosts:
            csr2:
...
